# Generated by Django 2.2.7 on 2019-11-19 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
