# Generated by Django 2.2.6 on 2019-12-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundations', '0003_instrument_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredians', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=255)),
                ('cooking', models.CharField(max_length=255)),
                ('culture', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='timeseriesdatum',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='TimeSeriesDatum',
        ),
    ]
